<?php
declare(strict_types=1);
$dir = __DIR__ . DIRECTORY_SEPARATOR . 'data';
$file = $dir . DIRECTORY_SEPARATOR . 'admin-config.php';
if (!is_dir($dir)) @mkdir($dir, 0755, true);
$already = is_file($file);
$message = '';
$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$already) {
    $password = (string)($_POST['password'] ?? '');
    $confirm = (string)($_POST['confirm'] ?? '');
    if (strlen($password) < 12) {
        $error = 'Use at least 12 characters for your admin password.';
    } elseif ($password !== $confirm) {
        $error = 'The passwords do not match.';
    } else {
        $hash = password_hash($password, PASSWORD_DEFAULT);
        $content = "<?php\n// Generated by setup-admin.php. Do not share this file.\nreturn ['password_hash' => " . var_export($hash, true) . "];\n";
        if (file_put_contents($file, $content, LOCK_EX) === false) {
            $error = 'Could not write data/admin-config.php. Make sure the data folder is writable.';
        } else {
            @chmod($file, 0640);
            $already = true;
            $message = 'Admin password created. You can now sign in.';
        }
    }
}
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="robots" content="noindex,nofollow">
  <title>Set up blog admin</title>
  <link rel="stylesheet" href="assets/css/style.css">
  <style>
    .setup-wrap{max-width:720px;margin:70px auto;padding:0 24px}.setup-card{border:1px solid #d8d8d2;border-radius:18px;padding:34px;background:#fff}.setup-card label{display:block;margin:18px 0}.setup-card input{width:100%;padding:13px 14px;margin-top:7px}.setup-msg{margin-top:18px}.setup-ok{color:#17643a}.setup-err{color:#b33a22}
  </style>
</head>
<body>
<main class="setup-wrap">
  <div class="setup-card">
    <p class="eyebrow">Admin setup</p>
    <h1>Set your blog password</h1>
    <?php if ($message): ?><p class="setup-msg setup-ok"><?= htmlspecialchars($message) ?></p><?php endif; ?>
    <?php if ($error): ?><p class="setup-msg setup-err"><?= htmlspecialchars($error) ?></p><?php endif; ?>

    <?php if ($already): ?>
      <p>Your admin password has already been configured. This setup page is now locked.</p>
      <p><a class="button" href="admin.html">Go to blog admin</a></p>
      <p><small>To intentionally reset the password later, delete <code>data/admin-config.php</code> from your own server, revisit this page, and create a new one.</small></p>
    <?php else: ?>
      <p>Create the password you will use to access the private blog editor. It is stored as a secure password hash, not as readable text.</p>
      <form method="post" autocomplete="off">
        <label>New admin password
          <input type="password" name="password" minlength="12" required autocomplete="new-password">
        </label>
        <label>Confirm password
          <input type="password" name="confirm" minlength="12" required autocomplete="new-password">
        </label>
        <button class="button" type="submit">Create admin password</button>
      </form>
    <?php endif; ?>
  </div>
</main>
</body>
</html>
