<?php
declare(strict_types=1);
$dir = __DIR__ . DIRECTORY_SEPARATOR . 'data';
$file = $dir . DIRECTORY_SEPARATOR . 'nowpayments-config.php';
if (!is_dir($dir)) @mkdir($dir, 0755, true);
$already = is_file($file);
$message = '';
$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$already) {
    $apiKey = trim((string)($_POST['api_key'] ?? ''));
    $ipnSecret = trim((string)($_POST['ipn_secret'] ?? ''));
    $publicUrl = rtrim(trim((string)($_POST['public_url'] ?? '')), '/');

    if (strlen($apiKey) < 12) {
        $error = 'Enter your NOWPayments API key.';
    } elseif (strlen($ipnSecret) < 12) {
        $error = 'Enter your NOWPayments IPN secret key.';
    } elseif ($publicUrl !== '' && !filter_var($publicUrl, FILTER_VALIDATE_URL)) {
        $error = 'The public site URL is not valid.';
    } else {
        $config = [
            'api_key' => $apiKey,
            'ipn_secret' => $ipnSecret,
            'public_url' => $publicUrl,
        ];
        $content = "<?php\n// Generated by setup-payments.php. Keep private and never commit this file.\nreturn " . var_export($config, true) . ";\n";
        if (file_put_contents($file, $content, LOCK_EX) === false) {
            $error = 'Could not write data/nowpayments-config.php. Make sure the data folder is writable.';
        } else {
            @chmod($file, 0640);
            $already = true;
            $message = 'NOWPayments credentials saved. Crypto checkout is ready.';
        }
    }
}
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="robots" content="noindex,nofollow">
  <title>Set up NOWPayments</title>
  <link rel="stylesheet" href="assets/css/style.css">
  <style>
    .setup-wrap{max-width:760px;margin:70px auto;padding:0 24px}.setup-card{border:1px solid #d8d8d2;border-radius:18px;padding:34px;background:#fff}.setup-card label{display:block;margin:18px 0;font-weight:700}.setup-card input{width:100%;padding:13px 14px;margin-top:7px}.setup-msg{margin-top:18px}.setup-ok{color:#17643a}.setup-err{color:#b33a22}.setup-card small{font-weight:400;line-height:1.5;display:block;margin-top:5px}
  </style>
</head>
<body>
<main class="setup-wrap">
  <div class="setup-card">
    <p class="eyebrow">Payment setup</p>
    <h1>Connect NOWPayments</h1>
    <?php if ($message): ?><p class="setup-msg setup-ok"><?= htmlspecialchars($message) ?></p><?php endif; ?>
    <?php if ($error): ?><p class="setup-msg setup-err"><?= htmlspecialchars($error) ?></p><?php endif; ?>

    <?php if ($already): ?>
      <p>NOWPayments has already been configured on this server. This setup page is locked.</p>
      <p><a class="button" href="index.html">Go to the donation page</a></p>
      <p><small>To intentionally replace the credentials later, delete <code>data/nowpayments-config.php</code> from your own server and revisit this page.</small></p>
    <?php else: ?>
      <p>Your API credentials are stored only on the PHP server and are never sent to visitors' browsers.</p>
      <form method="post" autocomplete="off">
        <label>NOWPayments API key
          <input type="password" name="api_key" required autocomplete="off">
          <small>NOWPayments Dashboard → API Settings → Add new key.</small>
        </label>
        <label>IPN secret key
          <input type="password" name="ipn_secret" required autocomplete="off">
          <small>Generate this in NOWPayments Store Settings. Save it carefully because NOWPayments may display it only once.</small>
        </label>
        <label>Public website URL <span style="font-weight:400">(optional while using XAMPP)</span>
          <input type="url" name="public_url" placeholder="https://yourdomain.com">
          <small>After moving to Hostinger, set this to the live site URL so NOWPayments can send payment-status callbacks to your website.</small>
        </label>
        <button class="button" type="submit">Save NOWPayments settings</button>
      </form>
    <?php endif; ?>
  </div>
</main>
</body>
</html>
